apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-test-deployment
spec:
  selector:
    matchLabels:
      app: cluster-test-pod
  template:
    metadata:
      labels:
        app: cluster-test-pod
    spec:
      containers:
      - name: cluster-test-container
        image: cluster-test:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
